version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env-db-dev

  app:
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    command: python manage.py runserver 0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env-app-dev
    depends_on:
      - db

volumes:
  postgres-data: