version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=strawberry-dev
      - POSTGRES_USER=strawberry
      - POSTGRES_PASSWORD=strawberry

  web:
    build: ./app
    command: python manage.py runserver 0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env-dev
    depends_on:
      - db

volumes:
  postgres-data: