version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env-db-prod

  app:
    build:
      context: ./app
      dockerfile: Dockerfile-prod
    command: gunicorn strawberry.wsgi:application --bind 0:8000
    volumes:
      - static:/home/app/app/static
      - media:/home/app/app/media
    expose:
      - 8000
    env_file:
      - ./.env-app-prod
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - static:/home/app/app/static
      - media:/home/app/app/media
    ports:
      - 1337:80
    depends_on:
      - app

volumes:
  postgres-data:
  static:
  media: