version: '3'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env-db-prod

  app:
    build:
      context: ./app
      dockerfile: Dockerfile-prod
    command: gunicorn strawberry.wsgi:application --bind 0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env-app-prod
    depends_on:
      - db

volumes:
  postgres-data: