version: '3'

services:
  db:
    container_name: db
    image: postgres:12-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env-db-prod

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile-prod
    command: gunicorn strawberry.wsgi:application --bind 0:8000
    volumes:
      - static:/home/app/app/static
      - media:/home/app/app/media
    expose:
      - 8000
    env_file:
      - ./.env-backend-prod
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env-frontend
    depends_on:
      - backend

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static:/home/app/app/static
      - media:/home/app/app/media
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres-data:
  static:
  media: